services:
  client:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    env_file: ./frontend/.env
    environment:
      - VITE_API_URL=http://localhost:3000/todo
    depends_on:
      - server
    networks:
      - my_network
  server:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    env_file: ./backend/.env
    depends_on:
      - mongodb
    networks:
      - my_network  
  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    networks:
      - my_network
volumes: 
  db-data:
networks:
  my_network:
    driver: bridge
